blog/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from blog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^TAKI/$', views.taki, name='taki'),
]

blurry/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    # body = models.TextField()
    body = RichTextField()

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    # 文章摘要
    # excerpt = models.CharField(max_length=200, blank=True)
    excerpt = RichTextField()

    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者,从 django.contrib.auth.models 导入
    author = models.ForeignKey(User)

    # 原作者,转载文章时可以填原作者
    authorship = models.CharField(max_length=20, blank=True)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post


def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', locals())


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/detail.html', locals())


def taki(request):
    post = get_object_or_404(Post, pk=1)
    return render(request, 'blog/TAKI.html', locals())

templates/blog/TAKI.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block body %}
    <div class="container">

        {#BLURR丶YE#}
        <div class="row">
            <div class="col-md-12">
                <div id="blurry" class="text-center">
                    Blurr の YE
                </div>
            </div>
        </div>

        {#导航#}
        <div class="row">
            <div class="col-md-12">
                <nav id="navbar" class="navbar navbar-inverse" role="navigation">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">New</a>
                        </div>

                        <div class="navbar-header">
                            <span class="navbar-brand">&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                        </div>

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Category</a>
                        </div>

                        <div class="navbar-header">
                            <span class="navbar-brand">&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                        </div>

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Mail</a>
                        </div>

                    </div>
                </nav>
            </div>
        </div>

        {#导航条下方的主体部分#}
        <div class="row">

            {#左#}
            <div class="col-md-3">
                <div class="text-center">
                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1521810423278&di=aacc257f72a0f4f762ba04bb4dd0cbe2&imgtype=0&src=http%3A%2F%2Fp4.gexing.com%2FG1%2FM00%2F9D%2FBA%2FrBACE1J94jrDGTMTAABS_00Yi-E359.jpg"
                         alt="眼镜">
                </div>

                <div id="left-content">
                    <div id="nickname">
                        <strong>BLURRYE</strong>
                    </div>
                    <div id="desc">
                        只要是在锅里煎过的鸡蛋，
                        <br/>
                        不管变成什么样子都是煎鸡蛋哦！
                    </div>
                </div>
            </div>

            {#中，正文#}
            <div class="col-md-6">

                <div id="post-excerpt">
                    {{ post.excerpt|safe }}
                </div>

                <div id="post-body">

                    <div class="text-center">
                        <h1>{{ post.title }}</h1>
                        {% if post.authorship %}
                            <small>作者：{{ post.authorship }}</small>
                            <br><br>
                        {% endif %}
                    </div>

                    {{ post.body|safe }}
                    
                </div>

            </div>

            {#右#}
            <div class="col-md-3">

            </div>
        </div>

    </div>
{% endblock %}

templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->

    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    {% block title %}
        <title>...</title>
    {% endblock %}

    <!-- css -->
    <link href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css.css' %}" rel="stylesheet">

    <!-- HTML5 Shim 和 Respond.js 用于让 IE8 支持 HTML5元素和媒体查询 -->
    <!-- 注意： 如果通过 file://  引入 Respond.js 文件，则该文件无法起效果 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

{% block body %}

    <div class="container">
        <h1>Hello,world!</h1>
    </div>

{% endblock %}

<hr>

<footer class="text-center">
    <div>
        Copy right &#169;
        <a href="#">blurry</a>
        2018
        <br><br>
    </div>
</footer>

<!-- css -->
<script href="{% static 'jquery-3.3.1.min.js' %}"></script>
<script href="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block body %}
    <div class="container">

        {#BLURR丶YE#}
        <div class="row">
            <div class="col-md-12">
                <div id="blurry" class="text-center">
                    Blurr の YE
                </div>
            </div>
        </div>

        {#导航#}
        <div class="row">
            <div class="col-md-12">
                <nav id="navbar" class="navbar navbar-inverse" role="navigation">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">New</a>
                        </div>

                        <div class="navbar-header">
                            <span class="navbar-brand">&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                        </div>

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Category</a>
                        </div>

                        <div class="navbar-header">
                            <span class="navbar-brand">&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                        </div>

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Mail</a>
                        </div>

                    </div>
                </nav>
            </div>
        </div>

        {#导航条下方的主体部分#}
        <div class="row">

            {#左#}
            <div class="col-md-3">
                <div class="text-center">
                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1521810423278&di=aacc257f72a0f4f762ba04bb4dd0cbe2&imgtype=0&src=http%3A%2F%2Fp4.gexing.com%2FG1%2FM00%2F9D%2FBA%2FrBACE1J94jrDGTMTAABS_00Yi-E359.jpg"
                         alt="眼镜">
                </div>

                <div id="left-content">
                    <div id="nickname">
                        <strong>BLURRYE</strong>
                    </div>
                    <div id="desc">
                        只要是在锅里煎过的鸡蛋，
                        <br/>
                        不管变成什么样子都是煎鸡蛋哦！
                    </div>
                </div>
            </div>

            {#中，正文#}
            <div class="col-md-6">

                <div id="post-excerpt">
                    {{ post.excerpt|safe }}
                </div>

                <div id="post-body">

                    <div class="text-center">
                        <h1>{{ post.title }}</h1>
                        {% if post.authorship %}
                            <small>作者：{{ post.authorship }}</small>
                            <br><br>
                        {% endif %}
                    </div>

                    {{ post.body|safe }}

                </div>

            </div>

            {#右#}
            <div class="col-md-3">

            </div>
        </div>

    </div>
{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    <title>index</title>
{% endblock %}

{% block body %}
    <div class="container">

        {#BLURR丶YE#}
        <div class="row">
            <div class="col-md-12">
                <div id="blurry" class="text-center">
                    Blurr の YE
                </div>
            </div>
        </div>

        {#导航#}
        <div class="row">
            <div class="col-md-12">
                <nav id="navbar" class="navbar navbar-inverse" role="navigation">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">New</a>
                        </div>

                        <div class="navbar-header">
                            <span class="navbar-brand">&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                        </div>

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Category</a>
                        </div>

                        <div class="navbar-header">
                            <span class="navbar-brand">&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                        </div>

                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Mail</a>
                        </div>

                    </div>
                </nav>
            </div>
        </div>

        <div class="row">
            {#左#}
            <div class="col-md-3">
                <div class="text-center">
                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1521810423278&di=aacc257f72a0f4f762ba04bb4dd0cbe2&imgtype=0&src=http%3A%2F%2Fp4.gexing.com%2FG1%2FM00%2F9D%2FBA%2FrBACE1J94jrDGTMTAABS_00Yi-E359.jpg" alt="眼镜">
                </div>

                <div id="left-content">
                    <div>
                        <br />
                        <strong>BLURRYE</strong>
                    </div>
                        <hr id="hr-left" />
                    <div>
                        只要是在锅里煎过的鸡蛋，
                        <br />
                        不管变成什么样子都是煎鸡蛋哦！
                    </div>
                </div>
            </div>
            {#中#}
            <div class="col-md-6">
                <ul>
                    {% for post in post_list %}
                        <li>
                            <a href="{% url 'blog:detail' post.pk %}">
                                {{ post.title }}
                            </a>
                            <br/>
                            {{ post.excerpt|safe }}
                        </li>
                    {% empty %}
                        暂无博文！
                    {% endfor %}
                </ul>
            </div>
            {#右#}
            <div class="col-md-3">

            </div>
        </div>

    </div>
{% endblock %}